concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - main
  workflow_dispatch:

name: default
jobs:
  default:
    permissions:
      actions: read
      contents: write
      issues: read
      packages: write
      pull-requests: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Release
        id: get-release
        run: |
          RELEASE=$(gh release view --json tagName --jq '.tagName' -R siderolabs/talos)
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "release=$RELEASE" >> $GITHUB_OUTPUT

          KERNEL_IMAGE_TAG="${RELEASE}-${GITHUB_SHA::8}"
          echo "KERNEL_IMAGE_TAG=$KERNEL_IMAGE_TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout talos
        uses: actions/checkout@v5
        with:
          repository: siderolabs/talos
          ref: ${{ steps.get-release.outputs.release }}
          path: talos

      - name: Get pkgs Commit
        id: get-pkgs-commit
        run: |
          COMMIT=$(sed -r 's/v[0-9]\.[0-9]+\.[0-9]+-[0-9]+-g([a-f0-9]{6})/\1/' talos/pkg/machinery/gendata/data/pkgs)
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT

      - name: Checkout pkgs
        uses: actions/checkout@v5
        with:
          repository: siderolabs/pkgs
          ref: ${{ steps.get-pkgs-commit.outputs.commit }}
          path: pkgs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: |
          which yq || sudo apt-get update && sudo apt-get install -y yq
          KERNEL_MAJOR_MINOR=v$(yq -r '.vars.linux_version' pkgs/Pkgfile |grep -oP '^[0-9]\.[0-9]+(?=\.[0-9])')

          curl -Lo merge_config.sh "https://raw.githubusercontent.com/torvalds/linux/refs/tags/${KERNEL_MAJOR_MINOR}/scripts/kconfig/merge_config.sh"
          chmod +x merge_config.sh

          cp -a patches/* pkgs/kernel/build/patches/
          make kernel-olddefconfig

          for cfg_file in config/*.cfg; do
            echo merging "$cfg_file"
            ./merge_config.sh -m pkgs/kernel/build/config-amd64 "$cfg_file"
          done

          cd pkgs
          make kernel PLATFORM=linux/amd64 USERNAME=${{ github.repository_owner }} TAG=$KERNEL_IMAGE_TAG

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}

      - name: Push kernel package to registry
        working-directory: pkgs
        run: |
          make kernel PLATFORM=linux/amd64 USERNAME=${{ github.repository_owner }} TAG=$KERNEL_IMAGE_TAG PUSH=true

      - name: Base
        working-directory: talos
        env:
          IMAGE_REGISTRY: registry.dev.siderolabs.io
          PLATFORM: linux/amd64,linux/arm64
          PUSH: "true"
        run: |
          KERNEL_IMAGE="ghcr.io/${{ github.repository_owner }}/talos-kernel:${KERNEL_IMAGE_TAG}"
          make talosctl-linux-amd64 kernel sd-boot sd-stub initramfs installer-base imager talos PKG_KERNEL="$KERNEL_IMAGE"

      - name: checkout extensions
        uses: actions/checkout@v5
        with:
          path: talos/_out/extensions
          ref: main
          repository: siderolabs/extensions

      - name: unshallow-extensions
        working-directory: talos
        run: |
          git -C _out/extensions fetch --prune --unshallow

      - name: set variables
        working-directory: talos
        run: |
          cat _out/talos-metadata >> "$GITHUB_ENV"

      - name: build extensions
        working-directory: talos
        env:
          PLATFORM: linux/amd64
          PUSH: "true"
          USERNAME: ${{ github.repository_owner }}
        run: |
          make all extensions-metadata -C _out/extensions

      - name: installer extensions
        working-directory: talos
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          make installer-with-extensions
