concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Talos version to build against (e.g. v1.11.0). If empty, uses latest release."
        type: string
        required: false
        default: ""

name: default
jobs:
  default:
    permissions:
      actions: read
      contents: write
      packages: write

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create custom installer images
        working-directory: talos
        env:
          USERNAME: ${{ github.repository_owner }}
        run: |
          docker run --rm -t -v $PWD/_out:/out ghcr.io/${USERNAME}/imager:v1.11.0 installer --platform=metal --system-extension-image ghcr.io/siderolabs/gvisor:20231214.0-v1.11.0@sha256:548b2b121611424f6b1b6cfb72a1669421ffaf2f1560911c324a546c7cee655e --system-extension-image ghcr.io/siderolabs/intel-ucode:20231114@sha256:ea564094402b12a51045173c7523f276180d16af9c38755a894cf355d72c249d
